# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d42b15148062e44512f000d39453af6f5533aaafae4a2a8575a1b4496fb8a867970e4c81e47c46108d58af8affcf3acde50ed8ef3f198a7169b32f3ebbfc9a

test:
  secret_key_base: 24136eeec39d2dd19342e8653449d27a72f8bed6fac1da6d72b3aef8ce370edfca8bc6fcc73b35ff4dea7a450db6491b292db3b9a236fc7e34150ea4fab904a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
